{
  "@context": "https://security.alpinelinux.org/static/context.jsonld",
  "id": "https://security.alpinelinux.org/branch/edge-community",
  "items": [
    {
      "@context": "https://security.alpinelinux.org/static/context.jsonld",
      "cpeMatch": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "cpeUri": "cpe:2.3:a:freeimage_project:freeimage:3.18.0:*:*:*:*:*:*:*",
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12212#cpeMatch/91398",
          "maximumVersion": "3.18.0",
          "maximumVersionOp": "==",
          "minimumVersion": null,
          "minimumVersionOp": "==",
          "package": "https://security.alpinelinux.org/srcpkg/freeimage",
          "type": "CPEMatch",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2019-12212"
        }
      ],
      "cvss3": {
        "score": 7.5,
        "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "description": "When FreeImage 3.18.0 reads a special JXR file, the StreamCalcIFDSize function of JXRMeta.c repeatedly calls itself due to improper processing of the file, eventually causing stack exhaustion. An attacker can achieve a remote denial of service attack by sending a specially constructed file.",
      "id": "https://security.alpinelinux.org/vuln/CVE-2019-12212",
      "ref": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12212#ref/60256",
          "referenceType": "Exploit",
          "rel": "https://sourceforge.net/p/freeimage/discussion/36111/thread/e06734bed5/",
          "type": "Reference"
        }
      ],
      "state": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": false,
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12212#state/17474",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/freeimage/3.18.0-r2",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2019-12212"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": false,
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12212#state/17650",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/freeimage/3.18.0-r2",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2019-12212"
        }
      ],
      "type": "Vulnerability"
    },
    {
      "@context": "https://security.alpinelinux.org/static/context.jsonld",
      "cpeMatch": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "cpeUri": "cpe:2.3:a:freeimage_project:freeimage:3.18.0:*:*:*:*:*:*:*",
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12214#cpeMatch/91400",
          "maximumVersion": "3.18.0",
          "maximumVersionOp": "==",
          "minimumVersion": null,
          "minimumVersionOp": "==",
          "package": "https://security.alpinelinux.org/srcpkg/freeimage",
          "type": "CPEMatch",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2019-12214"
        }
      ],
      "cvss3": {
        "score": 7.5,
        "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "description": "In FreeImage 3.18.0, an out-of-bounds access occurs because of mishandling of the OpenJPEG j2k_read_ppm_v3 function in j2k.c. The value of l_N_ppm comes from the file read in, and the code does not consider that l_N_ppm may be greater than the size of p_header_data.",
      "id": "https://security.alpinelinux.org/vuln/CVE-2019-12214",
      "ref": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12214#ref/60264",
          "referenceType": "Exploit",
          "rel": "https://sourceforge.net/p/freeimage/discussion/36111/thread/e06734bed5/",
          "type": "Reference"
        }
      ],
      "state": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": false,
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12214#state/17475",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/freeimage/3.18.0-r2",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2019-12214"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": false,
          "id": "https://security.alpinelinux.org/vuln/CVE-2019-12214#state/17651",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/freeimage/3.18.0-r2",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2019-12214"
        }
      ],
      "type": "Vulnerability"
    }
  ],
  "type": "Collection"
}